pub mod config;
pub mod content;
pub mod document;
pub mod error;
pub mod links;
pub mod renderer;
pub mod search;
pub mod synctex;
pub mod toc;
pub mod web;
pub mod widget;
pub mod zotero;

pub use config::{load_config, save_config, load_session, save_session, list_sessions, move_sessions_dir, Config, Session, SessionDoc};
pub use content::ContentSource;
pub use document::Document;
pub use error::{Result, TuiPdfError};
pub use links::LinkState;
pub use renderer::{compute_stripe_count, render_page, render_page_dpi, split_into_stripes, StripeCache};
pub use search::SearchState;
pub use synctex::{jump_to_neovim, send_forward, socket_path, synctex_edit, synctex_view, synctex_positions, SyncTexResult, SyncTexForward, SyncTexPosition};
pub use toc::{TocState, TocWidget};
pub use web::{WebContent, capture_url};
pub use widget::{PdfViewState, PdfWidget, StatusBar};
pub use zotero::{latest_pdf, load_library, lookup_by_path, ZoteroEntry, ZoteroLibrary};
